-- ============================================================
-- FLEET FORCE — Oracle Database Schema
-- Target: Oracle 26ai Free (FREEPDB1) / User: fleet_force
-- ============================================================

-- ==================== CLEANUP ====================
BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

-- ==================== HR & AUTH ====================

CREATE TABLE department (
    dept_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    dept_name     VARCHAR2(100) NOT NULL,
    budget        NUMBER(15,2) DEFAULT 0
);

CREATE TABLE roles (
    role_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name     VARCHAR2(50) NOT NULL UNIQUE,
    access_level  NUMBER(1) NOT NULL CHECK (access_level BETWEEN 1 AND 5)
);

CREATE TABLE employee (
    emp_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    emp_code      VARCHAR2(20) NOT NULL UNIQUE,
    first_name    VARCHAR2(100) NOT NULL,
    last_name     VARCHAR2(100),
    email         VARCHAR2(150),
    phone         VARCHAR2(20),
    dept_id       NUMBER REFERENCES department(dept_id),
    is_active     NUMBER(1) DEFAULT 1
);

CREATE TABLE employee_roles (
    emp_id        NUMBER REFERENCES employee(emp_id),
    role_id       NUMBER REFERENCES roles(role_id),
    assigned_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (emp_id, role_id)
);

CREATE TABLE app_user (
    user_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    display_name  VARCHAR2(100),
    emp_id        NUMBER REFERENCES employee(emp_id),
    role_id       NUMBER REFERENCES roles(role_id),
    avatar_url    VARCHAR2(200),
    last_login    TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==================== HUBS & ROUTING ====================

CREATE TABLE hub (
    hub_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    hub_name      VARCHAR2(100) NOT NULL,
    city          VARCHAR2(100) NOT NULL,
    state         VARCHAR2(100),
    address       VARCHAR2(200),
    latitude      NUMBER(10,6) NOT NULL,
    longitude     NUMBER(10,6) NOT NULL,
    manager_emp_id NUMBER REFERENCES employee(emp_id),
    is_active     NUMBER(1) DEFAULT 1
);

CREATE TABLE route (
    route_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    route_name    VARCHAR2(100),
    origin_hub_id NUMBER REFERENCES hub(hub_id),
    dest_hub_id   NUMBER REFERENCES hub(hub_id),
    distance_km   NUMBER(10,2),
    est_hours     NUMBER(6,2),
    is_active     NUMBER(1) DEFAULT 1
);

CREATE TABLE route_waypoint (
    waypoint_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    route_id      NUMBER NOT NULL REFERENCES route(route_id),
    seq_no        NUMBER NOT NULL,
    latitude      NUMBER(10,6) NOT NULL,
    longitude     NUMBER(10,6) NOT NULL
);

-- ==================== FLEET ====================

CREATE TABLE tractor (
    tractor_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    reg_no        VARCHAR2(20) NOT NULL UNIQUE,
    make          VARCHAR2(50) NOT NULL,
    model         VARCHAR2(100) NOT NULL,
    year_of_mfg   NUMBER(4),
    horsepower_hp NUMBER(6),
    peak_torque_nm NUMBER(6),
    gvw_kg        NUMBER(10),
    fuel_tank_l   NUMBER(6),
    num_axles     NUMBER(2) DEFAULT 3,
    insurance_expiry  DATE,
    pollution_cert_exp DATE,
    odometer_km   NUMBER(10,1) DEFAULT 0,
    status        VARCHAR2(20) DEFAULT 'Available',
    home_hub_id   NUMBER REFERENCES hub(hub_id),
    current_lat   NUMBER(10,6),
    current_lng   NUMBER(10,6),
    image_path    VARCHAR2(200),
    last_gps_ping TIMESTAMP,
    health_score  NUMBER(5,1) DEFAULT 100,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trailer (
    trailer_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    trailer_code  VARCHAR2(20) NOT NULL UNIQUE,
    trailer_type  VARCHAR2(30) NOT NULL,
    make          VARCHAR2(50),
    manufacture_year NUMBER(4),
    capacity_kg   NUMBER(10),
    capacity_m3   NUMBER(8,2),
    length_m      NUMBER(5,2),
    status        VARCHAR2(20) DEFAULT 'Available',
    home_hub_id   NUMBER REFERENCES hub(hub_id),
    image_path    VARCHAR2(200),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE driver (
    driver_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER REFERENCES employee(emp_id),
    first_name    VARCHAR2(100) NOT NULL,
    last_name     VARCHAR2(100),
    date_of_birth DATE,
    license_no    VARCHAR2(30) NOT NULL UNIQUE,
    license_type  VARCHAR2(20) DEFAULT 'HMV',
    license_expiry DATE,
    experience_yrs NUMBER(3,1),
    driver_rating NUMBER(3,1) DEFAULT 4.0,
    phone         VARCHAR2(20),
    email         VARCHAR2(150),
    emergency_contact VARCHAR2(20),
    blood_group   VARCHAR2(5),
    status        VARCHAR2(20) DEFAULT 'Available',
    current_hub_id NUMBER REFERENCES hub(hub_id),
    current_lat   NUMBER(10,6),
    current_lng   NUMBER(10,6),
    photo_path    VARCHAR2(200),
    total_trips   NUMBER DEFAULT 0,
    total_km      NUMBER(10,1) DEFAULT 0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE maintenance (
    maint_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tractor_id    NUMBER NOT NULL REFERENCES tractor(tractor_id),
    maint_type    VARCHAR2(50) NOT NULL,
    maint_date    DATE NOT NULL,
    cost          NUMBER(10,2),
    odometer_reading NUMBER(10,1),
    service_center VARCHAR2(100),
    notes         VARCHAR2(500),
    next_due_date DATE
);

CREATE TABLE telemetry (
    telemetry_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tractor_id    NUMBER NOT NULL REFERENCES tractor(tractor_id),
    latitude      NUMBER(10,6),
    longitude     NUMBER(10,6),
    speed_kmh     NUMBER(5,1),
    engine_load_pct NUMBER(5,1),
    fuel_level_pct NUMBER(5,1),
    recorded_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==================== CRM ====================

CREATE TABLE customer (
    customer_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    company_name  VARCHAR2(150) NOT NULL,
    contact_person VARCHAR2(100),
    email         VARCHAR2(150),
    phone         VARCHAR2(20),
    gst_no        VARCHAR2(20),
    acct_status   VARCHAR2(20) DEFAULT 'Active',
    contract_type VARCHAR2(20) DEFAULT 'Regular',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE address (
    address_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER NOT NULL REFERENCES customer(customer_id),
    label         VARCHAR2(50),
    street        VARCHAR2(200),
    city          VARCHAR2(100) NOT NULL,
    state         VARCHAR2(100),
    pincode       VARCHAR2(10),
    is_default    NUMBER(1) DEFAULT 0
);

CREATE TABLE contract (
    contract_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER REFERENCES customer(customer_id),
    contract_name VARCHAR2(100),
    start_date    DATE,
    end_date      DATE,
    sla_tier      VARCHAR2(20) DEFAULT 'Standard',
    rate_per_km   NUMBER(8,2),
    monthly_value NUMBER(12,2),
    status        VARCHAR2(20) DEFAULT 'Active',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE complaint (
    complaint_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER NOT NULL REFERENCES customer(customer_id),
    description   VARCHAR2(1000),
    status        VARCHAR2(20) DEFAULT 'Open',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at   TIMESTAMP
);

-- ==================== WAREHOUSE & INVENTORY ====================

CREATE TABLE category (
    category_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cat_name      VARCHAR2(100) NOT NULL,
    is_hazmat_class NUMBER(1) DEFAULT 0,
    description   VARCHAR2(200)
);

CREATE TABLE vendor (
    vendor_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    company_name  VARCHAR2(150) NOT NULL,
    contact_person VARCHAR2(100),
    email         VARCHAR2(150),
    phone         VARCHAR2(20),
    vendor_rating NUMBER(3,1) DEFAULT 3.0
);

CREATE TABLE product (
    product_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sku           VARCHAR2(30) UNIQUE,
    product_name  VARCHAR2(150) NOT NULL,
    category_id   NUMBER REFERENCES category(category_id),
    vendor_id     NUMBER REFERENCES vendor(vendor_id),
    unit_weight_kg NUMBER(8,2),
    unit_price    NUMBER(10,2)
);

CREATE TABLE warehouse (
    warehouse_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    warehouse_name VARCHAR2(100) NOT NULL,
    wh_type       VARCHAR2(30) DEFAULT 'Warehouse',
    hub_id        NUMBER REFERENCES hub(hub_id),
    address       VARCHAR2(200),
    area_sqft     NUMBER(10),
    is_temp_ctld  NUMBER(1) DEFAULT 0,
    capacity_pct  NUMBER(5,1) DEFAULT 0,
    total_capacity NUMBER(10) DEFAULT 10000,
    current_stock NUMBER(10) DEFAULT 0,
    dock_count    NUMBER(3) DEFAULT 4,
    dock_available NUMBER(3) DEFAULT 4,
    status        VARCHAR2(20) DEFAULT 'Active',
    manager_name  VARCHAR2(100),
    contact_phone VARCHAR2(20),
    inbound_today NUMBER DEFAULT 0,
    outbound_today NUMBER DEFAULT 0
);

CREATE TABLE bin_location (
    bin_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    warehouse_id  NUMBER NOT NULL REFERENCES warehouse(warehouse_id),
    zone          VARCHAR2(10),
    rack          VARCHAR2(10),
    shelf         VARCHAR2(10),
    is_occupied   NUMBER(1) DEFAULT 0
);

CREATE TABLE bin_product (
    bin_id        NUMBER REFERENCES bin_location(bin_id),
    product_id    NUMBER REFERENCES product(product_id),
    quantity      NUMBER(10),
    last_updated  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (bin_id, product_id)
);

-- ==================== ORDERS & LOADS ====================

CREATE TABLE orders (
    order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER REFERENCES customer(customer_id),
    contract_id   NUMBER REFERENCES contract(contract_id),
    status        VARCHAR2(30) DEFAULT 'Pending',
    priority      VARCHAR2(10) DEFAULT 'Medium',
    total_weight_kg NUMBER(10,2),
    order_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expected_delivery DATE
);

CREATE TABLE order_item (
    item_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id      NUMBER REFERENCES orders(order_id),
    product_id    NUMBER REFERENCES product(product_id),
    quantity      NUMBER(10),
    weight_kg     NUMBER(10,2)
);

CREATE TABLE trip (
    trip_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    route_id      NUMBER REFERENCES route(route_id),
    tractor_id    NUMBER REFERENCES tractor(tractor_id),
    trailer_id    NUMBER REFERENCES trailer(trailer_id),
    driver_id     NUMBER REFERENCES driver(driver_id),
    planned_start TIMESTAMP,
    actual_start  TIMESTAMP,
    planned_end   TIMESTAMP,
    actual_end    TIMESTAMP,
    status        VARCHAR2(30) DEFAULT 'Planned',
    fuel_consumed_l NUMBER(8,2),
    distance_km   NUMBER(10,2),
    current_lat   NUMBER(10,6),
    current_lng   NUMBER(10,6),
    progress_pct  NUMBER(5,2) DEFAULT 0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE load (
    load_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    load_code     VARCHAR2(20) NOT NULL UNIQUE,
    order_id      NUMBER REFERENCES orders(order_id),
    customer_id   NUMBER REFERENCES customer(customer_id),
    trip_id       NUMBER REFERENCES trip(trip_id),
    pickup_hub_id NUMBER REFERENCES hub(hub_id),
    dropoff_hub_id NUMBER REFERENCES hub(hub_id),
    status        VARCHAR2(30) DEFAULT 'Unassigned',
    priority      VARCHAR2(10) DEFAULT 'Medium',
    rate          NUMBER(10,2),
    margin_pct    NUMBER(5,1),
    cargo_desc    VARCHAR2(200),
    cargo_weight_kg NUMBER(10,2),
    is_return_empty NUMBER(1) DEFAULT 0,
    pickup_date   TIMESTAMP,
    delivery_date TIMESTAMP,
    actual_delivery TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE load_timeline (
    timeline_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    load_id       NUMBER NOT NULL REFERENCES load(load_id),
    event_type    VARCHAR2(50) NOT NULL,
    event_desc    VARCHAR2(200),
    event_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE load_document (
    doc_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    load_id       NUMBER NOT NULL REFERENCES load(load_id),
    doc_type      VARCHAR2(50),
    file_name     VARCHAR2(200),
    file_path     VARCHAR2(500),
    uploaded_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE load_note (
    note_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    load_id       NUMBER NOT NULL REFERENCES load(load_id),
    user_id       NUMBER REFERENCES app_user(user_id),
    content       VARCHAR2(2000),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==================== SHIPMENT & DELIVERY ====================

CREATE TABLE shipment (
    shipment_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id      NUMBER REFERENCES orders(order_id),
    trip_id       NUMBER REFERENCES trip(trip_id),
    status        VARCHAR2(30) DEFAULT 'Pending',
    total_weight_kg NUMBER(10,2),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE package (
    package_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shipment_id   NUMBER NOT NULL REFERENCES shipment(shipment_id),
    barcode       VARCHAR2(30) UNIQUE,
    weight_kg     NUMBER(8,2),
    is_fragile    NUMBER(1) DEFAULT 0,
    description   VARCHAR2(200)
);

CREATE TABLE delivery (
    delivery_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shipment_id   NUMBER REFERENCES shipment(shipment_id),
    load_id       NUMBER REFERENCES load(load_id),
    status        VARCHAR2(30) DEFAULT 'Pending',
    scheduled_date DATE,
    actual_date   DATE,
    recipient_name VARCHAR2(100)
);

CREATE TABLE del_attempt (
    attempt_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    delivery_id   NUMBER NOT NULL REFERENCES delivery(delivery_id),
    attempt_no    NUMBER(2) DEFAULT 1,
    status        VARCHAR2(30),
    failure_reason VARCHAR2(200),
    attempted_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==================== FINANCE ====================

CREATE TABLE invoice (
    invoice_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    invoice_no    VARCHAR2(20) NOT NULL UNIQUE,
    order_id      NUMBER REFERENCES orders(order_id),
    load_id       NUMBER REFERENCES load(load_id),
    customer_id   NUMBER REFERENCES customer(customer_id),
    total_amount  NUMBER(12,2),
    tax_amount    NUMBER(10,2) DEFAULT 0,
    net_amount    NUMBER(12,2),
    due_date      DATE,
    status        VARCHAR2(20) DEFAULT 'Pending',
    payment_terms VARCHAR2(30) DEFAULT 'Net 30',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment (
    payment_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    invoice_id    NUMBER NOT NULL REFERENCES invoice(invoice_id),
    amount        NUMBER(12,2),
    payment_method VARCHAR2(30),
    payment_date  TIMESTAMP,
    reference_no  VARCHAR2(50),
    status        VARCHAR2(20) DEFAULT 'Pending'
);

-- ==================== SYSTEM & LOGGING ====================

CREATE TABLE notification (
    notif_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id       NUMBER REFERENCES app_user(user_id),
    title         VARCHAR2(100),
    message       VARCHAR2(500),
    notif_type    VARCHAR2(30) DEFAULT 'info',
    is_read       NUMBER(1) DEFAULT 0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
    audit_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    emp_id        NUMBER,
    table_name    VARCHAR2(50),
    action        VARCHAR2(20),
    record_id     NUMBER,
    old_values    CLOB,
    new_values    CLOB,
    performed_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE query_log (
    log_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sql_text      CLOB,
    sql_type      VARCHAR2(20),
    table_name    VARCHAR2(50),
    execution_ms  NUMBER(10),
    row_count     NUMBER,
    executed_by   VARCHAR2(50),
    executed_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add complaint FK to orders now that both tables exist
ALTER TABLE complaint ADD order_id NUMBER REFERENCES orders(order_id);

COMMIT;
